
import { ReportConfig } from "../../types";

const createTemplate = (
    id: string,
    title: string,
    desc: string,
    source: 'sales' | 'inventory' | 'customers' | 'purchases' | 'expenses',
    type: 'BAR' | 'LINE' | 'PIE' | 'TABLE' | 'AREA' | 'SCATTER' | 'COMPOSED' | 'KPI',
    groupBy: string,
    metricId: string,
    metricLabel: string,
    metricAgg: 'SUM' | 'AVG' | 'COUNT' | 'MIN' | 'MAX'
): ReportConfig => ({
    id,
    title,
    description: desc,
    dataSource: source,
    chartType: type,
    groupBy,
    fields: [
        { id: groupBy, label: groupBy.replace(/([A-Z])/g, ' $1').trim(), type: 'string' },
        { id: metricId, label: metricLabel, type: 'number', aggregation: metricAgg }
    ],
    filters: [],
    createdAt: Date.now()
});

export const REPORT_CATEGORIES = ['All', 'Sales', 'Inventory', 'Customers', 'Purchases', 'Financial'];

export const EXTENDED_PREBUILT_REPORTS: ReportConfig[] = [
    // --- SALES REPORTS (15) ---
    createTemplate('sales_by_customer', 'Sales by Customer', 'Total revenue generated by each customer', 'sales', 'BAR', 'customerName', 'totalAmount', 'Revenue', 'SUM'),
    createTemplate('sales_trend_daily', 'Daily Sales Trend', 'Revenue performance over time (Daily)', 'sales', 'LINE', 'date', 'totalAmount', 'Revenue', 'SUM'),
    createTemplate('sales_by_payment', 'Sales by Payment Method', 'Distribution of Cash, UPI, Cheque', 'sales', 'PIE', 'paymentMethod', 'totalAmount', 'Revenue', 'SUM'),
    createTemplate('sales_count_by_date', 'Transaction Volume Trend', 'Number of invoices generated per day', 'sales', 'AREA', 'date', 'id', 'Invoices', 'COUNT'),
    createTemplate('avg_order_value', 'Average Order Value (Daily)', 'Average transaction size per day', 'sales', 'LINE', 'date', 'totalAmount', 'Avg Order Value', 'AVG'),
    createTemplate('sales_by_month', 'Monthly Sales Performance', 'Total revenue aggregated by month', 'sales', 'BAR', 'month', 'totalAmount', 'Revenue', 'SUM'),
    createTemplate('sales_by_year', 'Yearly Revenue', 'Annual revenue performance', 'sales', 'BAR', 'year', 'totalAmount', 'Revenue', 'SUM'),
    createTemplate('discount_analysis', 'Discount Given Analysis', 'Total discounts provided to customers', 'sales', 'BAR', 'customerName', 'discount', 'Total Discount given', 'SUM'),
    createTemplate('sales_by_hour', 'Peak Sales Hours', 'Analysis of sales volume by time of day', 'sales', 'BAR', 'hour', 'totalAmount', 'Revenue', 'SUM'), // Requires engine support
    createTemplate('sales_vs_gst', 'GST Collection Trend', 'Tax collected over time', 'sales', 'LINE', 'date', 'gstAmount', 'GST Collected', 'SUM'),
    createTemplate('top_selling_products', 'Top Selling Products (Qty)', 'Most popular items by quantity', 'sales', 'BAR', 'productName', 'quantity', 'Qty Sold', 'SUM'), // Need line item expansion?
    createTemplate('sales_by_area', 'Sales by Region/Area', 'Revenue distribution by customer location', 'sales', 'PIE', 'customerArea', 'totalAmount', 'Revenue', 'SUM'),
    createTemplate('sales_weekend_weekday', 'Weekday vs Weekend Sales', 'Performance comparison', 'sales', 'PIE', 'isWeekend', 'totalAmount', 'Revenue', 'SUM'),
    createTemplate('return_vs_sales', 'Returns vs Sales', 'Impact of returns on revenue', 'sales', 'COMPOSED', 'month', 'netAmount', 'Net Revenue', 'SUM'),
    createTemplate('sales_forecast', 'Sales Forecast (Next 30 Days)', 'Predicted revenue based on trend', 'sales', 'LINE', 'date', 'forecastValue', 'Forecast', 'AVG'), // Advanced

    // --- INVENTORY REPORTS (10) ---
    createTemplate('inventory_value_category', 'Stock Value by Category', 'Capital tied up in each category', 'inventory', 'PIE', 'category', 'stockValue', 'Stock Value', 'SUM'),
    createTemplate('inventory_qty_category', 'Stock Quantity by Category', 'Item count distribution', 'inventory', 'BAR', 'category', 'quantity', 'Units', 'SUM'),
    createTemplate('low_stock_alert', 'Low Stock Items', 'Items below reorder point', 'inventory', 'TABLE', 'name', 'quantity', 'Current Stock', 'MIN'),
    createTemplate('high_value_items', 'High Value Inventory', 'Most expensive items in stock', 'inventory', 'BAR', 'name', 'purchasePrice', 'Unit Cost', 'MAX'),
    createTemplate('expiry_risk', 'Expiry Risk Analysis', 'Items expiring soon (requires batch tracking)', 'inventory', 'TABLE', 'name', 'expiryDate', 'Expiry', 'MIN'),
    createTemplate('margin_analysis', 'Profit Margin Analysis', 'Estimated margin (Sale - Cost)', 'inventory', 'BAR', 'name', 'marginPercent', 'Margin %', 'AVG'),
    createTemplate('stock_age', 'Stock Age Analysis', 'How long items have been in inventory', 'inventory', 'BAR', 'category', 'ageDays', 'Avg Age (Days)', 'AVG'),
    createTemplate('fast_vs_slow', 'Fast vs Slow Moving', 'Turnover rate by product', 'inventory', 'SCATTER', 'turnoverRate', 'quantity', 'Stock Level', 'AVG'),
    createTemplate('brand_distribution', 'Inventory by Brand', 'Stock distribution by manufacturer', 'inventory', 'PIE', 'brand', 'stockValue', 'Value', 'SUM'),
    createTemplate('damaged_stock', 'Damaged/Returned Stock', 'Value of non-sellable inventory', 'inventory', 'BAR', 'category', 'damagedQty', 'Damaged Units', 'SUM'),

    // --- CUSTOMER REPORTS (10) ---
    createTemplate('customer_balance', 'Outstanding Dues by Customer', 'Who owes the most money?', 'customers', 'BAR', 'name', 'dueAmount', 'Due Amount', 'SUM'),
    createTemplate('customer_acquisition', 'New Customers Over Time', 'Growth of customer base', 'customers', 'LINE', 'joinDate', 'id', 'New Signups', 'COUNT'),
    createTemplate('customer_ltv', 'Customer Lifetime Value', 'Total spend per customer', 'customers', 'BAR', 'name', 'totalSpent', 'LTV', 'SUM'),
    createTemplate('customer_geo', 'Customer Distribution by Area', 'Where are your customers located?', 'customers', 'PIE', 'area', 'id', 'Customer Count', 'COUNT'),
    createTemplate('inactive_customers', 'Inactive Customers (>90 Days)', 'Customers who haven\'t purchased recently', 'customers', 'TABLE', 'name', 'lastPurchaseDays', 'Days Since Purchase', 'MAX'),
    createTemplate('top_customers_freq', 'Frequent Buyers', 'Customers with most transactions', 'customers', 'BAR', 'name', 'transactionCount', 'Orders', 'SUM'),
    createTemplate('customer_tier', 'Customers by Pricing Tier', 'Retail vs Wholesale distribution', 'customers', 'PIE', 'priceTier', 'id', 'Count', 'COUNT'),
    createTemplate('loyalty_points', 'Loyalty Points Liability', 'Outstanding points to be redeemed', 'customers', 'BAR', 'name', 'loyaltyPoints', 'Points Balance', 'SUM'),
    createTemplate('credit_utilization', 'Credit Limit Utilization', 'Who is close to their credit limit?', 'customers', 'BAR', 'name', 'creditUtilization', 'Utilization %', 'AVG'),
    createTemplate('customer_profitability', 'Most Profitable Customers', 'Profit generated per customer', 'customers', 'BAR', 'name', 'totalProfit', 'Profit Contribution', 'SUM'),

    // --- PURCHASE & SUPPLIER REPORTS (10) ---
    createTemplate('purchase_by_supplier', 'Purchases by Supplier', 'Spend distribution per vendor', 'purchases', 'PIE', 'supplierName', 'totalAmount', 'Total Spend', 'SUM'),
    createTemplate('purchase_trend', 'Monthly Purchase Trend', 'Inventory buying patterns', 'purchases', 'LINE', 'month', 'totalAmount', 'Spend', 'SUM'),
    createTemplate('supplier_dues', 'Payables to Suppliers', 'Outstanding bills to vendors', 'purchases', 'BAR', 'supplierName', 'dueAmount', 'Payable', 'SUM'),
    createTemplate('purchase_vs_sales', 'Purchases vs Sales Ratio', 'Cash flow efficiency', 'purchases', 'COMPOSED', 'month', 'totalAmount', 'Outflow', 'SUM'),
    createTemplate('gst_input_credit', 'GST Input Credit', 'Tax paid on purchases', 'purchases', 'BAR', 'month', 'gstAmount', 'GST Input', 'SUM'),
    createTemplate('avg_purchase_cost', 'Average Purchase Order Size', 'Typical procurement value', 'purchases', 'LINE', 'date', 'totalAmount', 'Avg Order', 'AVG'),
    createTemplate('payment_due_schedule', 'Upcoming Payment Dues', 'Cash requirements for next 30 days', 'purchases', 'TABLE', 'dueDate', 'dueAmount', 'Amount Due', 'SUM'),
    createTemplate('top_supplied_items', 'Top Items by Spend', 'What are you spending most on?', 'purchases', 'BAR', 'productName', 'amount', 'Spend', 'SUM'),
    createTemplate('supplier_reliability', 'Supplier Delivery Time', 'Avg. days to receive goods', 'purchases', 'BAR', 'supplierName', 'deliveryDays', 'Days', 'AVG'),
    createTemplate('purchase_category', 'Spending by Category', 'Cost distribution', 'purchases', 'PIE', 'category', 'totalAmount', 'Spend', 'SUM'),

    // --- EXPENSE & FINANCIAL REPORTS (8) ---
    createTemplate('expense_by_category', 'Expenses by Category', 'Where is the money going?', 'expenses', 'PIE', 'category', 'amount', 'Expense', 'SUM'),
    createTemplate('expense_monthly', 'Monthly Expense Trend', 'Operational costs over time', 'expenses', 'LINE', 'month', 'amount', 'Cost', 'SUM'),
    createTemplate('expense_vs_revenue', 'Revenue vs Expenses', 'Operating Ratio', 'expenses', 'COMPOSED', 'month', 'amount', 'Expense', 'SUM'),
    createTemplate('profit_loss_trend', 'Net Profit Trend', 'Bottom line performance', 'sales', 'AREA', 'month', 'netProfit', 'Net Profit', 'SUM'),
    createTemplate('cash_flow', 'Cash Flow Statement', 'Inflow vs Outflow', 'sales', 'BAR', 'month', 'cashFlow', 'Net Cash', 'SUM'),
    createTemplate('tax_liability', 'Estimated Tax Liability', 'Net GST Payable', 'sales', 'BAR', 'month', 'taxPayable', 'Tax Due', 'SUM'),
    createTemplate('salary_trend', 'Salary & Wages Trend', 'Labor cost analysis', 'expenses', 'LINE', 'month', 'amount', 'Salaries', 'SUM'), // Filter by cat=Salary
    createTemplate('rent_utilities', 'Rent & Utilities', 'Fixed cost tracking', 'expenses', 'BAR', 'month', 'amount', 'Fixed Costs', 'SUM'),
];
