
// Utility for Google Calendar API interactions

interface CalendarEvent {
    summary: string;
    description?: string;
    location?: string;
    startTime: string; // ISO String
    endTime?: string;  // ISO String (default 1 hour later)
}

export const createCalendarEvent = async (accessToken: string, event: CalendarEvent) => {
    try {
        const start = new Date(event.startTime);
        
        let end;
        if (event.endTime) {
            end = new Date(event.endTime);
        } else {
            // Default to 1 hour event
            end = new Date(start);
            end.setHours(end.getHours() + 1);
        }

        const eventResource = {
            summary: event.summary,
            description: event.description || 'Generated by Business Manager',
            location: event.location || '',
            start: {
                dateTime: start.toISOString(),
                timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
            },
            end: {
                dateTime: end.toISOString(),
                timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
            }
        };

        const response = await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${accessToken}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(eventResource)
        });

        if (!response.ok) {
            if (response.status === 401 || response.status === 403) {
                throw new Error("AUTH_ERROR");
            }
            const errorBody = await response.text();
            throw new Error(`Calendar API Error: ${response.status} ${errorBody}`);
        }

        return await response.json();
    } catch (error) {
        console.error("Failed to create calendar event", error);
        throw error;
    }
};
